#!/bin/sh

echo "===== Running pre-commit ====="
echo "===== pre-commit: running Pytest ====="

pytest

if [ $? -ne 0 ]
then
  echo "===== pre-commit: tests failed, aborting commit ====="
  exit 1
fi

echo "===== pre-commit: Success! Committing... ====="